# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337

checkpoint:
  save_interval_updates: 5000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: si_sdri
  maximize_best_checkpoint_metric: true

distributed_training:
  ddp_backend: c10d
  find_unused_parameters: true
  distributed_world_size: 1
  distributed_port: 29671
  nprocs_per_node: 1

task:
  _name: enhancement
  otf_data_simu: false
  data_dir: /scratch4/lgarci27/hzili1/workspace/Amazon/fairseq/examples/enhancement/dataset/
  crop_dur: 20.0
  rate: 16000
  n_fft: 512
  hop_length: 160
  win_length: 400
  chunk_size: 4.0
  target: direct

dataset:
  num_workers: 6
  batch_size: 32
  batch_size_valid: 1
  validate_after_updates: 0
  validate_interval_updates: 2000
  train_subset: train
  valid_subset: dev

criterion:
  _name: enh
  mask_type: PSM
  loss_type: L1
  n_fft: ${task.n_fft}
  hop_length: ${task.hop_length}
  win_length: ${task.win_length}

optimization:
  max_update: 50000
  lr: [1e-3]
  sentence_avg: false
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: enh_transformer 
  setup: tiny
  n_fft: ${task.n_fft}
  activation: none
  log1p: true
  pos_enc: conv

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - dataset.train_subset
          - dataset.valid_subset
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
